### ISSUE TITLE
Differenciate between Backspace and Ctrl+Backspace

### ISSUE THREAD

**Issue by jleclanche** [lxqt/qtermwidget#1]
Ctrl+Backspace on linux/macbook/Default sends the same signal as backspace, ^?. On vt420pc/solaris they're both ^H.

^H should be sent by "backspace" and ^? by "ctrl+backspace"; a Ctrl+V in xterm shows the proper behaviour.

**Comment by yan12125** [comment]
Here's a fix => #218
