### ISSUE TITLE
More compatible modified keys

### ISSUE THREAD

**Issue by bunnylin** [lxqt/qtermwidget#117]
qterminal 0.7.1 behaves differently from xterm and lxterminal with these key inputs:

qterminal produces no input for numpad 5 in any mode. These are the expected inputs:
numpad 5: [E
Shift + numpad 5 (with numlock on): [1;2E
Alt + numpad 5: [1;3E
Ctrl + numpad 5: [1;5E

Numpad 2/4/6/8 produce the same input regardless of modifiers in all modes except linux mode. Is there any reason not to make the modified numpad keys produce unique inputs in other modes?

Ctrl+enter produces character 13 in all qterminal modes, which is just a normal enter. In xterm, I get [27;5;13~ and in lxterminal I get character 10.

**Comment by yan12125** [comment]
> qterminal produces no input for numpad 5 in any mode.

Here's a patch for this:
```Diff
diff --git a/lib/KeyboardTranslator.cpp b/lib/KeyboardTranslator.cpp
index 856fadb..3cbee16 100644
--- a/lib/KeyboardTranslator.cpp
+++ b/lib/KeyboardTranslator.cpp
@@ -617,7 +617,7 @@ bool KeyboardTranslator::Entry::matches(int keyCode ,
         return false;
 
     // if modifiers is non-zero, the 'any modifier' state is implicit
-    if ( modifiers != 0 )
+    if ( (modifiers & ~Qt::KeypadModifier) != 0 )
         testState |= AnyModifierState;
 
     if ( (testState & _stateMask) != (_state & _stateMask) )
diff --git a/lib/kb-layouts/default.keytab b/lib/kb-layouts/default.keytab
index aebd8cf..2345c59 100644
--- a/lib/kb-layouts/default.keytab
+++ b/lib/kb-layouts/default.keytab
@@ -167,3 +167,6 @@ key Next  +Shift-AppScreen  : scrollPageDown
 
 key ScrollLock     : scrollLock
 
+
+key Clear -AnyMod+KeyPad+AppKeyPad : "\E[E"
+key Clear +AnyMod+KeyPad+AppKeyPad : "\E[1;*E"
```

I don't know why 5 generates Key_Clear in Qt...

> Ctrl+enter produces character 13 in all qterminal modes, which is just a normal enter. In xterm, I get [27;5;13~ and in lxterminal I get character 10.

I got ```^M``` (0x13) in all terminals. At least .bashrc/.zshrc, .inputrc can change this result. terminfo (part of ncurses on most systems) and the shell you use may be related, too. Could you try with "clean" shells:
```bash --norc --noprofile``` or ```zsh --norcs```?

**Comment by bunnylin** [comment]
Nice, thank you for the numpad patch!

I have a minimal .bashrc, which shouldn't make a difference, and no .zshrc/.inputrc; I'm reading the keypresses using the standard read() system call, so ncurses isn't involved. Running either bash --norc --noprofile or zsh --norcs does not change the result; if the underlying terminal normally prints a different Ctrl+enter, it still does so if running a clean shell in the terminal. Might locale make a difference? Mine is en-US.UTF-8.

- The plain Linux fullscreen tty prints 0x13 for enter and numpad enter with any modifier.
- urxvt prints 0x13 for enter with any modifier. Shift+numpad enter produces OM.
- LXterminal prints 0x10 for Ctrl+enter, Alt+enter, and Ctrl+numpad enter.
- xterm prints  [27;2;13~ for Shift+enter and  [27;5;13~ for Ctrl+enter; Alt+enter toggles fullscreen. In normal mode, numpad enter produces 0x13 with all modifiers. In application keypad mode (ctrl+middle click on window), numpad enter is OM, with shift O2M, with alt O3M, with ctrl O5M.
- qterminal produces 0x13 for any enter, except default/macbook mode produces OM for Shift+enter.

It's not critically important, of course. I don't imagine too many terminal programs look for modified enters.

**Comment by yan12125** [comment]
Thanks for such detailed testing results! This can be a good reference for similar issues.

As they are quite different, I guess terminal applications will not expect a universal response from the Enter key with modifiers, so I'd like to keep this part unchanged until it really breaks some application. If a future reader comes to this issue, feel free to open another issue with concrete usages.

For the numpad 5 part, I'll need to check why Key_Clear is mapped before opening a pull request.

**Comment by yan12125** [comment]
In PR #276, I fixed numpad 5 with numlock off for cases not involving Shift. See the commit message for why Shift is not implemented.

**Comment by yan12125** [comment]
Numpad 5 is now fixed. I don't plan to fix Enter until there is a standard among popular terminal implementations.
