### ISSUE TITLE
Python bindings are broken

### ISSUE THREAD

**Issue by DonnieWest** [lxqt/qtermwidget#135]
Sorry, forgot to open an issue for #134 

b1f37a882c2d9aaa5816fbaf68eaedb38178b428 seems to have caused build errors on the Python bindings that looks like

```
In file included from qtermwidget.sip:11:0:
./../lib/qtermwidget.h:27:10: fatal error: qtermwidget_export.h: No such file or directory
 #include "qtermwidget_export.h"
          ^~~~~~~~~~~~~~~~~~~~~~
```

#134 should fix that and add some missing python bindings. Someone who _actually_ knows what they're doing should look it over though. Feel free to open a proper pull request to address these issue but I'd also love it if someone would tell me what I'm doing wrong so I can fix it.

**Comment by yan12125** [comment]
ping @luis-pereira, the author of b1f37a8

If I understand it correctly, reverting b1f37a8 prevents qterminal from correctly building?

Some ideas:
1. Build the python binding in CMakeLists.txt
2. Separate core C++ part and Python binding - users have to build and install core C++ part first and then build Python binding

IMO 1. is better

**Comment by luis-pereira** [comment]
Acknowledged. Will fix it ASAP.

**Comment by nilsholle** [comment]
Has there any progress been made concerning this issue?
We'd really like to integrate QTerminal in a PyQt project.

**Comment by agaida** [comment]
@nilsholle - no progress, no python manpower - we accept patches

**Comment by luis-pereira** [comment]
@yan12125 @agaida @nilsholle @DonnieWest Ready to test.
