### ISSUE TITLE
qt-virt-manager license violation

### ISSUE THREAD

**Issue by agaida** [lxqt/qtermwidget#169]
##### Current Behavior

Was playing a bit with https://github.com/F1ash/qt-virt-manager - after  a short view i noticed that all of our license headers are stripped and some file are used without any attribution - @pvanek, i guess mostly your work. Filed a bug https://github.com/F1ash/qt-virt-manager/issues/32

##### Possible Solution
They (he) should re-introduce the license headers again - if not we should build a little bit pressure until fixed.

##### Context

Downstream project use our code without attribution.

**Comment by F1ash** [comment]
[fixed for me](https://github.com/F1ash/qt-virt-manager/issues/32#issuecomment-368828010)
