### ISSUE TITLE
Deprecation warning CMP0002 in pyqt/CMakeLists.txt

### ISSUE THREAD

**Issue by agaida** [lxqt/qtermwidget#177]
Version: current git, cmake version 3.11.1, Qt 5.10.1
```
CMake Deprecation Warning at pyqt/CMakeLists.txt:4 (cmake_policy):
  The OLD behavior for policy CMP0002 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.
```

**Comment by agaida** [comment]
@luis-pereira - is there a special reason for OLD?

**Comment by luis-pereira** [comment]
@agaida I'm not sure if we can remove it.
Actually, the bindings seem to be broken with Qt5.11. Can anybody confirm ? @yan12125

**Comment by yan12125** [comment]
> Actually, the bindings seem to be broken with Qt5.11

Yep. It builds but does not run:
```
$ python -c 'import QTermWidget'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
RuntimeError: the PyQt5.QtCore module failed to register with the sip module
```

On Arch Linux with Qt 5.11.1, PyQt5 5.11.2 and sip 4.19.12.

2018-07-31 0:43 GMT+08:00 Luís Pereira <notifications@github.com>:

**Comment by yan12125** [comment]
@DonnieWest is the pyqt binding for qtermwidget still working for you?

**Comment by DonnieWest** [comment]
It's not been working for me on Arch Linux :/

**Comment by yan12125** [comment]
Thank you for the feedback @DonnieWest. Anyone got working PyQt binding for QTermWidget on other systems with Qt 5.11?

**Comment by agaida** [comment]
@yan12125 - we need some people who are really interested in working bindings - qgis might be worth a look, they use an embeded qterminal imho. not sure about python. It's only a idea - but if they use phyton we should talk with them.

**Comment by yan12125** [comment]
QGIS uses the C++ interface. Actually they bundle an old copy of qtermwidget. cool-retro-term and qt-virt-manager are similar. I don't know who are using the PyQt binding besides those who have submitted relevant patches (DonnieWest).

**Comment by DonnieWest** [comment]
I actually stopped using the python bindings personally - I needed something a bit more stable and switched to the C++ interface

**Comment by raboof** [comment]
Not at the moment, no

**Comment by yan12125** [comment]
Thanks for the feedback. Then we should try to fix it instead of dropping it.

@pawelkoston Mind sharing build details? (OS/distribution, commands, outputs, etc.)

**Comment by pawelkoston** [comment]
I am using a Gentoo based distribution and I am able to build against: PyQt5-5.10.1-r1 and dev-python/sip-4.19.8. 
I use the old python script for building:  https://github.com/pawelkoston/qtermwidget/tree/master/pyqt 
PyQt 5.11 is not yet marked as stable, for my distribution so I am not expecting it to work correctly.  I was able to build QTermwidget against PyQt5==5.11.3
PyQt5-sip==4.19.13
installed from pip, but I was unable to run it, because of an error:
```
Traceback (most recent call last):
  File "./test.py", line 25, in <module>
    import QTermWidget
ValueError: PyCapsule_GetPointer called with incorrect name
```

**Comment by luis-pereira** [comment]
@agaida The CMP002 can be safely removed.
@yan12125 
I was able to build and run the python binding (Qt 5.9.5)
Check the log: https://pastebin.com/raw/ma5JcKaB
and the binding test being run (using the https://github.com/lxqt/qtermwidget/pull/258 PR)
https://imgur.com/a/Q76UZBN

**Comment by yan12125** [comment]
Thanks for bringing this up. QTermWidget should support Qt 5.11+ sooner or later, and moving to PySide2 might be an option (#249).
