### ISSUE TITLE
add qmake

### ISSUE THREAD

**Issue by rahmanshaber** [lxqt/qtermwidget#181]
please add a qmake .
and also for the example.

**Comment by yan12125** [comment]
I consider it too much work to maintain two build systems. If you have a working draft, feel free to create a pull request and I may add it to community contributions.

**Comment by agaida** [comment]
without a really good reason we shouldn't support additional build systems - btw. "But i want qmake" is not a good reason.

**Comment by yan12125** [comment]
Right. I don't object if someone is willing to provide and maintain a qmake pro file, but seems it's not the case here, so closing.
