### ISSUE TITLE
free(): invalid pointer (Version 0.9.0)

### ISSUE THREAD

**Issue by testtube123** [lxqt/qtermwidget#185]
Whenever I open qterminal I get : free(): invalid pointer

##### Current Behavior

QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-testube123'
Properties constructor called
TRANSLATIONS_DIR: Loading translation file "qterminal_en_US.qm" from dir /usr/share/qterminal/translations
load success: false
QDir::exists: Empty or null file name
Canot open file "/home/testube123/.config/qterminal.org/qterminal_bookmarks.xml"
Trying to load translation file from dir "/usr/local/share"
Trying to load translation file from dir "/usr/share"
Trying to load translation file from dir "/usr/share/qtermwidget5/translations"
default KB_LAYOUT_DIR:  "/usr/share/qtermwidget5/kb-layouts"
loadAllColorSchemes
default KB_LAYOUT_DIR:  "/usr/share/qtermwidget5/kb-layouts"

##### Possible Solution

file ------> new tab or ctrl-shift-t

##### System Information

* Distribution & Version: Gentoo
* Kernel: 4.17.2-gentoo
* Qt Version: 5.9.4
* qtermwidget Version: 0.9.0
* lxqt-build-tools Version: 0.5.0
* Package version : 0.9.0

**Comment by agaida** [comment]
and please start from the very beginning  - at least have a look at the build order. to make it short i would start with qtxdg.

**Comment by testtube123** [comment]
Alright will do

**Comment by agaida** [comment]
Isn't meant harsh - i packaged LXQt from the scratch back in 2014 - and i know there are some pitfalls - and the trap the very most people hit is not to follow the build order - and libqtxdg is our most important lib - all packages depend on a current qtxdg - https://forum.lxqt.org/t/build-order-release-plan/292
