### ISSUE TITLE
Colorschemes loading from user directory

### ISSUE THREAD

**Issue by concatime** [lxqt/qtermwidget#192]
**This is not a bug, but rather a feature request.**
It would be nice if we could load colorsheme files from '.config' or '.local'.
Maybe `.local/share/qtermwidget5/color-schemes/`, or `.local/share/konsole/`, or `.config/qterminal/color-schemes/`, …

**Comment by agaida** [comment]
just use $HOME/.config/qterminal.org/color-schemes/ and place your color-schemes there.
