### ISSUE TITLE
Cannot change the $TERM environment variable

### ISSUE THREAD

**Issue by jonasjaguar** [lxqt/qtermwidget#206]
So, either I am stupid or I've found a little issue/bug.
So, my problem is, that I, no matter what I do, can't change the $TERM environment variable.
This is really weird.

##### Expected Behavior
At least one of the lines should change the $TERM variable to "xterm-256color".

##### Current Behavior
When I run the program from the command line, it
(kinda) changes the variable, but really weird.
I'll list tested cases here:  
Behaviour when:  
* Running from Qt Creator: Variable does not change, it stays containing "dumb".  
* Running with a double-click on executable: Variable does not change, it stays containing "dumb".  
* Running via a .desktop file (without kioclient5): Variable does not change, it stays containing "dumb".
* Running via a .desktop file (with kioclient5): Variable does not change, it stays containing "dumb".
* Running via command line: So this is really weird. It changes the variable (at least I think), but the variable is not changed to the value I specified, it is changed to the $TERM variable value of the underlying terminal.

##### Possible Solution
I **really** don't know, but I would really appreciate it if you could provide a
solution. I am very stuck and found nothing in over 8 hours of searching and trial-and-error.

##### Current code (not working)
```
setenv("TERM", "xterm-256color", 1);
qDebug() << getenv("TERM"); // Outputs "xterm-256color" when running from command line / Qt Creator
QSettings settings("JaguDev", "Commander");
settings.setValue("Term", "xterm-256color"); // I've seen this somewhere in the QTerminal code
QStringList env = QProcess::systemEnvironment();
env << "TERM=xterm-256color";
this->ui->centralWidget->setEnvironment(env); // An example included in the Qt Docs
```
(In case you wonder, the centralWidget is the QTermWidget)

##### Context
As I said, I want to change the $TERM environment variable
for my QTermWidget named centralWidget.

##### System Information
* Distribution & Version: KDE neon 5.13.4
* Kernel: 4.15.0-33-generic
* Qt Version: 5.11.1
* liblxqt Version:  0.10.0-1ubuntu1
* Package version: 0.6.0+20160108-3 (libqtermwidget5-0)

##### Note
Sorry for my bad english

**Comment by yan12125** [comment]
`setenv()` should work. You may want to check your `.bashrc`/`.zshrc`/... to see if `$TERM` is modified.

By the way,

> liblxqt Version: 0.10.0-1ubuntu1
> Package version: 0.6.0+20160108-3 (libqtermwidget5-0)

Both are too old. The relevant issues might have been fixed.

**Comment by jonasjaguar** [comment]
@yan12125 
Okay, I found it out now.
I set the environment variable *after* I created the QTermWidget,
I should have set it *before* the initialization.
Many thanks!
