### ISSUE TITLE
Underlines of detected links are not correctly positioned with non-zero terminal margin

### ISSUE THREAD

**Issue by yan12125** [lxqt/qtermwidget#209]
##### Expected Behavior
Underlines of detected links are always correctly positioned no matter what the value of the terminal margin (https://github.com/lxqt/qtermwidget/pull/205) is.

##### Current Behavior
When the terminal margin is set to a large value (e.g. 20px), underlines no longer attach to links.

![default](https://user-images.githubusercontent.com/1937689/45555858-801a8300-b86c-11e8-88b4-89cc15095876.png)

##### Possible Solution
Need investigation

##### Steps to Reproduce (for bugs)
1. Set the terminal margin to 20px via preferences
2. Type "echo https://example.com"
3. Move the mouse around the link

##### Context
Edge case of #205

##### System Information
* Distribution & Version: Arch Linux latest
* Kernel: Linux 4.18.7-arch1-1-ARCH
* Qt Version: 5.11.1-3
* Package version: git-master

**Comment by Admicos** [comment]
Yep, happens over here too.

**Comment by Admicos** [comment]
I'm not entirely sure but I think this is because `void TerminalDisplay::paintFilters(QPainter& painter)` (TerminalDisplay.cpp:1431) doesn't account for the terminal margin.
