### ISSUE TITLE
Dunno how this line work with margins

### ISSUE THREAD

**Issue by agaida** [lxqt/qtermwidget#213]
https://github.com/lxqt/qtermwidget/blob/6d1be93f680140296be0fa6a0bf5b84c6f4adacf/lib/TerminalDisplay.cpp#L1530

@yan12125 - i really don't get it, but the whole mapping seems to be wrong, will add some lines to illustrate this. @tsujan - it would be nice if you could have a view too, it is absurd.

**Comment by tsujan** [comment]
`QCursor::pos()` gives the global cursor position and `mapFromGloba()l` translates it into the coordinates of the widget `TerminalDisplay`. On the other hand, `region` is also in that coordinate.

Although this was only a quick look and I might need to look into it more carefully, I first prefer to ask you what problem you see *in practice*. Have you encountered a bug? If there's a bug, I'll know what I should search for.

**Comment by tsujan** [comment]
Take your time.

**Comment by tsujan** [comment]
OK, I hadn't upgraded for a while; saw the new bug -- caused by new setting for margins -- minutes ago, after upgrading.

**Comment by tsujan** [comment]
Margins are buggy. An example:

![bug](https://user-images.githubusercontent.com/981076/45920311-04918500-beaf-11e8-80f6-37eae436866e.png)

Will look into it in my free time.

**Comment by agaida** [comment]
Thats why i ask - it boiled down to this damn line i can't interpret nor  debug nor fix :) - a few colorfull pictures will illustrate what i mean.

**Comment by tsujan** [comment]
> it boiled down to this damn line

Margins have complicated things. That line is only one factor that may be wrong with margins -- as you correctly guessed.

**Comment by tsujan** [comment]
I succeeded in fixing the bug with margins:

![fix](https://user-images.githubusercontent.com/981076/45920949-a9649000-beb8-11e8-9220-5b914c0e980e.png)

However, there may be other places that margins should be taken into account. So, let me scan the code before making a PR; it may take a while...

**Comment by agaida** [comment]
ok - did you base your things on the open PR #211 ?

**Comment by tsujan** [comment]
> ok - did you base your things on the open PR #211 ?

I saw it. Some of its lines were correct, some incorrect and some changes were required but missing from it -- scanning the code is about finding more required changes that don't affect links (I think there are still some).

**Comment by agaida** [comment]
ok, that would be nice if the changes would solve some problems we not even had encountered - i put all open qterm* bugs into https://github.com/orgs/lxqt/projects/2 - i'm selfish, i use qterminal on a daily base (>= 99,9%)

**Comment by tsujan** [comment]
When it's finished (not today), should I make changes to the branch `fix-underlines` or make a PR?

> i use qterminal on a daily base

I too :) But I don't upgrade it as soon as a commit is made.

**Comment by tsujan** [comment]
OK, contrary to my suspicions, there wasn't another issue related to margins.

But there is an old "issue" -- unimportant but still: when the cursor is on the last character of a link, it isn't underlined; underlining starts to happen when the cursor is on the last but one character.

Will also include a fix for that if it's easy.

**Comment by agaida** [comment]
ok, fixed in my branch :)

**Comment by agaida** [comment]
was only about the missed char :D - and i made somewhere a really dumb typo so i tried it from the scratch again - step by step - i have no problems just to drop that branch while you are on it.

**Comment by tsujan** [comment]
> was only about the missed char

Oh, yes! That seems correct. Sorry that I missed it!

> i have no problems just to drop that branch while you are on it.

And I'd have no problem to work on your branch but you've done some color customization there. Maybe you want to propose them in a separate PR later. I don't see why not.

**Comment by agaida** [comment]
the "color-customization" was only for debugging reasons

**Comment by tsujan** [comment]
At some point, we might be able to add a background to links by taking the font color into account.

On second thought, since some changes of https://github.com/lxqt/qtermwidget/pull/211 should be reversed, it'll be easier for me to make a PR by starting from the latest source.

**Comment by agaida** [comment]
no problem - git push remote origin :fix-underl..
