### ISSUE TITLE
Unable to find qtermwidget5 for compilation

### ISSUE THREAD

**Issue by ganimaedes** [lxqt/qtermwidget#214]
I'm trying to compile my code with cmake and with a compile_commands.json file. However it doesn't detect my qtermwidget5 installation directory when compiling and there's also no detection inside vim for code completion.

OS: `Ubuntu 16.04 LTS`
uname -a : `Linux ubuntu-gnome 4.8.0-36-generic #36~16.04.1-Ubuntu`
cmake --version: `cmake version 3.12.1`
CMakeLists.txt file contents:
```
cmake_minimum_required(VERSION 3.04)
project(minterm)

# Instruct CMake to run moc automatically when needed.
set(CMAKE_AUTOMOC ON)

# Find includes in corresponding build directories
set(CMAKE_INCLUDE_CURRENT_DIR ON)

include_directories(${Qt5Widgets_INCLUDES})

# Find the QtWidgets library
find_package(Qt5Widgets)
find_package(qtermwidget5)

add_definitions(${Qt5Widgets_DEFINITIONS})
set(CMAKE_CXX_FLAGS "${Qt5Widgets_EXECUTABLE_COMPILE_FLAGS}")

file(GLOB SOURCE *.h, *.cpp)

add_executable(minterm ${SOURCE})

# Use the Widgets module from Qt 5.
target_link_libraries(minterm Qt5::Widgets)
target_link_libraries(minterm ${Qt5Widgets_LIBRARIES})
```
I have installed all these with apt: `sudo apt install build-essential pkg-config autoconf qttools5-dev qttools5-dev-tools qtdeclarative5-dev qtdeclarative5-dev-tools qtbase5-dev qtbase5-dev-tools qt5-qmake software-properties-common python-software-properties libqt5xmlpatterns5-dev libqt5x11extras5-dev libqtermwidget5-0 qt5-default`

I have also tried to install it manually with an older version of lxqt tools by copying the zip in this link:
`https://github.com/lxqt/lxqt-build-tools/tree/b38c9e0d12877702f0d12b749f69579626c36054`
and then:
```
cd lxqt*
cmake -DCMAKE_PREFIX_PATH=/usr/include/x86_64-linux-gnu/qt5 \
      -DCMAKE_EXPORT_COMPILE_COMMANDS=YES \
      -DCMAKE_CXX_COMPILER=/usr/bin/g++-7 \
      -DCMAKE_BUILD_TYPE=Release  \
      -DCMAKE_INSTALL_PREFIX=/usr \
      -DCMAKE_INSTALL_LIBDIR=lib  \
      -DBUILD_DESIGNER_PLUGIN=0   \
      -DUSE_QT5=true .
make 
sudo make install
```
The same goes for qtermwidget with an older version:
```
unzip qtermwidget-0.7.1.zip
cd qtermwidget-0.7.1/
mkdir -p build 
cd build
cmake -DCMAKE_PREFIX_PATH=/usr/include/x86_64-linux-gnu/qt5 \
      -DCMAKE_EXPORT_COMPILE_COMMANDS=YES \
      -DCMAKE_CXX_COMPILER=/usr/bin/g++-7 .. \
      -DCMAKE_BUILD_TYPE=Release  \
      -DCMAKE_INSTALL_PREFIX=/usr \
      -DCMAKE_INSTALL_LIBDIR=lib  \
      -DBUILD_DESIGNER_PLUGIN=0   \
      -DUSE_QT5=true ..
make 
sudo make install 
```
I have decided to install older versions because qtermwidget wouldn't accept a Qt version older than Qt5.7.1. I have Qt5.5.1 installed for ubuntu 16.04. I cannot upgrade my Qt version and it isn't possible to choose Qtcreator and qmake to create my project.

Here's my compile_commands.json:
```
[
{
  "directory": "/home/<username>/min-term/build",
  "command": "/usr/bin/c++  -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NO_DEBUG -DQT_WIDGETS_LIB -D_POSIX_SOURCE -I/home/<username>/min-term/build -I/home/<username>/min-term -I/home/<username>/min-term/build/minterm_autogen/include -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -isystem /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64    -fPIC -o CMakeFiles/minterm.dir/minterm.cpp.o -c /home/<username>/min-term/minterm.cpp",
  "file": "/home/<username>/min-term/minterm.cpp"
}
```
I have created the file above with these commands:
```
[ -d "~/min-term/build" ] || mkdir -p ~/min-term/build
cd build; cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=YES ..
ln -s build/compile_commands.json ..
```
and when compiling my code:
```
cmake . -DCMAKE_PREFIX_PATH=/usr/include/x86_64-linux-gnu/qt5
make
./minterm
```
Ultimately, I would like to be able to run a sample program like this one (taken from [codekoalas)](https://codekoalas.com/blog/build-your-own-minimal-terminal) but qtermwidget.h doesn't get detected here and neither when compiling:
```
#include <QApplication>
#include <QKeySequence>
#include <QMainWindow>
#include <QtDebug>
#include "qtermwidget.h"

int main(int argc, char *argv[])
{
    QApplication app(argc, argv);
    QMainWindow *mainWindow = new QMainWindow();

    QTermWidget *console = new QTermWidget();

    QFont font = QApplication::font();
    font.setFamily("Monospace");
    font.setPointSize(12);

    console->setTerminalFont(font);
    qDebug() << " availableColorSchemes: " << console->availableColorSchemes();
    QObject::connect(console, SIGNAL(finished()), mainWindow, SLOT(close()));
    mainWindow->setCentralWidget(console);
    mainWindow->show();
    return app.exec();
}
```
Any ideas would be really helpful. Thank you.

**Comment by agaida** [comment]
Yes, we have ideas - don't use outdated LTS versions is the first one.
Second idea: Ubuntu uses the deb packaging format - i would suggest to use it.
(And no, i don't want to discuss it, done this to much in the past 10 years)
Third idea: LTS and bleeding edge packages will tend not to work, depending on the age of the LTS - so one should at least use 18.04.
