### ISSUE TITLE
Ctrl + Shift + C and Ctrl + C send same keys

### ISSUE THREAD

**Issue by DonnieWest** [lxqt/qtermwidget#225]
##### Steps to Reproduce (for bugs)

```
#include <QApplication>
#include <QDesktopServices>
#include <QKeySequence>
#include <QMainWindow>
#include <QtDebug>

#include "qtermwidget.h"

int main(int argc, char *argv[]) {
  QApplication app(argc, argv);
  QMainWindow *mainWindow = new QMainWindow();
  setenv("TERM", "xterm-256color", 1);

  QTermWidget *console = new QTermWidget();

  QFont font = QApplication::font();
  font.setFamily("monospace");
  font.setPixelSize(22);
  font.setWeight(QFont::Normal);

  console->setTerminalFont(font);
  console->setAutoClose(true);

  QObject::connect(console, &QTermWidget::termKeyPressed, mainWindow,
                  [=](const QKeyEvent *key) -> void {
                    qDebug() << key->text();
                    if (key->text() == "\u0003") {
                      console->copyClipboard();
                    } else if (key->text() == "\u0016") {
                      console->pasteClipboard();
                    }
                  });

  mainWindow->resize(1800, 3200);
  mainWindow->setCentralWidget(console);

  QObject::connect(console, SIGNAL(finished()), mainWindow, SLOT(close()));

  mainWindow->show();

  return app.exec();
}
```

If you look at the output of `qDebug` you'll see that Ctrl+Shift+C emits the same thing as Ctrl+C. It's possible I'm missing something though

##### System Information

* Distribution & Version: Latest Arch on latest git Qtermwidget

Picks up from #82 since there was continued discussion and confusion, but the issue was already closed

**Comment by yan12125** [comment]
Ctrl-C send 0x03. What should Ctrl-Shift-C send? Tried iTerm2 and it still sends 0x03 for Ctrl-Shift-C.

An option is using extended unicode CSI sequence proposed by libtermkey [1], but I wonder how many applications supports that.

[1] http://www.leonerd.org.uk/hacks/fixterms/

**Comment by yan12125** [comment]
In this case I guess QShortcut would fit your need - intercept Ctrl-Shift-C before it's passed to QTermWidget.

**Comment by DonnieWest** [comment]
Well, that was a simple solution. Sorry for the hassle

If you still think there's merit to adding those extended CSI sequences, feel free to keep this open. Otherwise, this solved my particular use case

**Comment by yan12125** [comment]
No problem!

> If you still think there's merit to adding those extended CSI sequences, feel free to keep this open.

No as of now, closing.
