### ISSUE TITLE
Update python bindings

### ISSUE THREAD

**Issue by maksbotan** [lxqt/qtermwidget#23]
Hi,
I see that python bindings for qtermwidgets are at least 4 years old and do not compile. For instance, in `pyqt4/qtermwidget.sip` file you need to fix argument to function `setColorScheme`, it's `const QString &name` now.
And I've checked and found out that API of qtermwidget has changed significantly during these 4 years. So, please update sip file to match current state of the API.
Thanks.

**Comment by agaida** [comment]
outdated and done
