### ISSUE TITLE
How to use the "QTermWidget" in PySide2?

### ISSUE THREAD

**Issue by haolimin118** [lxqt/qtermwidget#249]
##### Expected Behavior

Qt official has released their Qt for Python and PySide2 is popular .
How to use the QTermWidget in PySide2?
If it does not support PySide2, do you consider this in the future?

##### Steps to Reproduce (for bugs)

1. 
2. 
3. 
4. 

##### System Information

* Distribution & Version: 
* Kernel: 
* Qt Version: 
* liblxqt Version:  
* Package version:

**Comment by yan12125** [comment]
> If it does not support PySide2, do you consider this in the future?

Haven't look into details but I think only PyQt is supported for now. Patches for PySide2 are welcome!

**Comment by yan12125** [comment]
Not sure why the original author closed this issue. Patches for PySide2 are still welcome!
