### ISSUE TITLE
What exactly are the “macbook” and “solaris” terminals?

### ISSUE THREAD

**Issue by apjanke** [lxqt/qtermwidget#262]
This is more of a question than a bug report. What terminals are the “macbook” and “solaris” emulation modes referring to?

A MacBook is a hardware model, not a terminal. Does “macbook” refer to the Terminal.app program included with OS X/macOS?

And is “solaris” the CDE `dtterm` program (the default terminal emulator on Solaris, I think)?

I assume “linux” is the Linux console, and not Konsole/xterm/one of the other X11 terminal programs shipped with Linux?

**Comment by yan12125** [comment]
I'm not sure what's their purpose, either, but I'm sure those keybaord layouts are buggy, as only the `default` layout received fixes these days. `default` should work on all major platforms (Linux, macOS, \*BSD), so I plan to deprecate none-`default` layouts after fixing https://github.com/lxqt/qtermwidget/issues/235.

**Comment by apjanke** [comment]
Okay, I'll stick with `default`. Thanks.
