### ISSUE TITLE
Support gtk-primary-selection on Wayland (need Qt 5.14+)

### ISSUE THREAD

**Issue by yan12125** [lxqt/qtermwidget#278]
##### Expected Behavior
I can use the middle mouse button to copy and paste texts in Wayland.

##### Current Behavior
It doesn't work.

##### Possible Solution
The gtk-primary-selection protocol from GNOME seems useful. Qt 5.14 will support it [1]. The best outcome is that qtermwidget automatically get that ability if built with Qt 5.14. It may require some special treatment, too.

[1] https://bugreports.qt.io/browse/QTBUG-66008

##### Steps to Reproduce (for bugs)
1. Run Wayfire
2. Select some texts
3. Attempt to paste it with the middle mouse button

##### Context
Using the middle mouse button is handy :)

##### System Information
* Distribution & Version: Arch Linux x86_64
* Kernel: 5.1.9-arch1-1-ARCH
* Qt Version: 5.13.0rc2-2
* lxqt-build-tools Version: git-master
* Package version: git-master
* Wayfire version: r993.188dfd4-1

**Comment by agaida** [comment]
I have no problems with defaulting to 5.14 - ok, this is one of the changes that can't be backported to LTS  distributions, so we should take care. In this case i guess that some version based switches would be appropriate.

**Comment by yan12125** [comment]
Sure! Most likely the feature will be in a `#if` block. I'll keep qtermwidget compilable on all Qt LTS versions supported upstream (Qt 5.9 as of writing).

**Comment by yan12125** [comment]
I gave it a test. With qt5-wayland 5.14.0beta1-2 and sway 1:1.2-3, copy texts using the middle mouse button from qterminal to evince works. Qt devs are awesome as usual :smile:
