### ISSUE TITLE
is it possible to embed qterm widget in another qt5 application(like a code editor) as a widget?

### ISSUE THREAD

**Issue by jasonsun0310** [lxqt/qtermwidget#279]
##### Steps to Reproduce (for bugs)

1. 
2. 
3. 
4. 

##### System Information

* Distribution & Version: 
* Kernel: 
* Qt Version: 
* lxqt-build-tools Version: 
* Package version:

**Comment by yan12125** [comment]
Sure! I know Juffed uses qtermwidget. Octave uses a fork of qtermwidget, too.

**Comment by yan12125** [comment]
Sure! I know Juffed uses qtermwidget. Octave uses a fork of qtermwidget, too.
