### ISSUE TITLE
Travis CI fails to build

### ISSUE THREAD

**Issue by shlyakpavel** [lxqt/qtermwidget#295]
##### Expected Behavior
Every good PR is built successfully 

##### Current Behavior
Any PR fails to build
##### Possible Solution
Fix Travis configuration

##### Steps to Reproduce (for bugs)
1. Create Pull Request on GitHub
2. Enjoy

##### Context
https://github.com/lxqt/qtermwidget/pull/294 https://github.com/lxqt/qtermwidget/pull/293 https://github.com/lxqt/qtermwidget/pull/292

**Comment by yan12125** [comment]
The syntax of our .travis.yml is no longer accepted. I've created https://github.com/mikkeloscar/arch-travis/issues/60 to ask if it's possible to re-allow such an usage.

**Comment by shlyakpavel** [comment]
@yan12125 can we temporary downgrade arch-travis version to something more reliable than master?

**Comment by yan12125** [comment]
Here is a workaround: https://github.com/lxqt/qtermwidget/pull/296

Downgrading is not possible as it requires an older arch-travis Docker image, which is no longer available :/

**Comment by yan12125** [comment]
Upstream fix is merged. I've restarted tests of 3 aforementioned pull requests, and all of them are now green. Time for more joy!
