### ISSUE TITLE
output symbols are shown as squares or not shown at all

### ISSUE THREAD

**Issue by kinoegit** [lxqt/qtermwidget#308]
@lxqt-team and supporters
I'm running **octopi**-git, a pacman frontend from the AUR on Arch linux/ KDE Plasma. 
Octopi-git is using **qterminal** in **qtermwidget** as embedded terminal.
But its output looks like this: https://imgur.com/vn9OROj
It seems that all areas of potentially input of the embedded terminal= qtermwidget are '**squared**'. All other areas particular of pure output are fine. 
Strange that **qterminal** used as standalone works flawlessly?!
I tried quite a few things: https://github.com/aarnt/octopi/issues/401
Is this familiar to someone here? Any ideas would be appreciated... 'cause this is a tough one.

KDE Plasma Version: 5.17.3
KDE Frameworks Version: 5.64.0
Qt Version: 5.13.2
Kernel Version: 5.3.12-arch1-1
Qtermwidget-git version: 0.14.1.47.gd4896ed-1
Qterminal-git version: 0.14.1.75.g1ce29eb-1

**Comment by kinoegit** [comment]
I found the problem... it is sitting 2ft in front of the monitor ;-)
Once I installed manually a font called 'Monospace.ttf' which perhaps was in conflict with
font.setFamily("Monospace") in qtermwidget.h or with other fonts of the monospace family because itself isn't a monospace font!
Anyway, uninstalling it solved the problem!

**Comment by yan12125** [comment]
Ah, glad to see the culprit found LOL
