### ISSUE TITLE
SearchBar dark theme white text over white background

### ISSUE THREAD

**Issue by daniruiz** [lxqt/qtermwidget#312]
Currently `SearchBar::clearBackgroundColor()` forces the search bar background to white, which works fine with a light theme. But if you use a dark theme with light font color it can't be readable.

![Captura de pantalla_2019-12-04_22-43-13](https://user-images.githubusercontent.com/12565871/70237942-82664700-1768-11ea-97fc-d1737107c5b1.png)

##### Expected Behavior

The search bar background should maintain the theme's background

![image](https://user-images.githubusercontent.com/12565871/70239114-face0780-176a-11ea-88e2-49feea0dbe14.png)

##### Current Behavior

The search bar is forced to change its background color to white, overriding the theme's one

##### Possible Solution
I'm not a Qt developer but I've found that instead of using `p.setColor(QPalette::Base, Qt::white)` palette `QWidget::window()->palette()` restores the widget background using the theme's colors.

##### Steps to Reproduce (for bugs)

1. Change Qt theme to a dark one
2. Open Qterminal
3. Open search bar (Ctrl + Shift + F)
4. Write anything that matches a string in the console

##### Context

I frequently use the search bar

##### System Information

* Distribution & Version: Kali Linux
* Kernel: 5.3.0 amd64
* Qt Version: 5.12.5
* lxqt-build-tools Version: 0.6.0
* Package version: git master

**Comment by yan12125** [comment]
The proposed solution seems correct. Mind to open a pull request?

**Comment by daniruiz** [comment]
Done :wink: #315

**Comment by yan12125** [comment]
When I'm trying to reproduce the bug, I noticed that Kvantum seems to just ignore requests to set the background color - when there are no matches, the background does not become red. /cc @tsujan

**Comment by tsujan** [comment]
> I noticed that Kvantum seems to just ignore requests to set the background color 

Yes, Kvantum resists intrusions, as far as possible.

I didn't follow this issue -- QTerminal's search-bar has never had a problem here (with Kvantum, of course) -- but drawing a widget is much more than adding background + foreground: if a widget needs to be drawn differently (Why?! That will break widget styles!), either `QStyle` or a Qt style sheet should be used in a complete way.

**Comment by tsujan** [comment]
Frankly, I didn't understand the problem -- sorry if I'm missing something obvious but I didn't have time to find what `SearchBar::clearBackgroundColor()` does. This is QTerminal's search-bar with a dark and also a light Kvantum theme:

![qterminal](https://user-images.githubusercontent.com/981076/70858693-ff897d00-1f1b-11ea-845f-4fb01b138de7.png)

**Comment by daniruiz** [comment]
Now that the PR is merged this can be closed
Thanks :wink:

**Comment by yan12125** [comment]
> Frankly, I didn't understand the problem 

From my previous testing, the search bar issue existed only in Breeze dark, not Kvantum.

**Comment by tsujan** [comment]
Off topic:

I saw the light red bg with `qterminal -style fusion`.

It isn't important but, if I find the time, I'll make a PR for the text color -- instead of the base color. It's possible to find a different text color that has enough contrast with the (unchanged) base color, so that it breaks no style.
