### ISSUE TITLE
Add #define QTERMWIDGET_VERSION

### ISSUE THREAD

**Issue by axkibe** [lxqt/qtermwidget#331]
Hello, I recently integerated qtermwidget to TeXStudio. Now there is this "issue":
https://github.com/texstudio-org/texstudio/issues/1008
On Travis it tries to build against an older version that doesn't have `setTerminalSizeHint()`.

I know one "solution" would be instead of lib-depending to qtermwidget to copy/paste the whole source tree and integrate it in the TeXStudio build system. However I'd prefer not to, as this creates a fork which is probably going to be much less maintained.

##### Expected Behavior

Not that it change the older versions out there, but I'd really like a VERSION #define I could #ifdef to, either to adapt to older versions, or to #error with the correct message to get a newer version.

##### Current Behavior

I don't see a way in source code to "see" what qtermwidget version it is going to be compiled against.

##### Possible Solution

see above, something along this (in case of cmake but hoewever this is done)
#define PROJECT_NAME "@PROJECT_NAME@"
#define PROJECT_VER  "@PROJECT_VERSION@"
#define PROJECT_VER_MAJOR "@PROJECT_VERSION_MAJOR@"
#define PROJECT_VER_MINOR "@PROJECT_VERSION_MINOR@"
#define PTOJECT_VER_PATCH "@PROJECT_VERSION_PATCH@"

##### System Information

* Distribution & Version: 
* Kernel: 
* Qt Version: 
* lxqt-build-tools Version: 
* Package version: 

Yes, old Ubunter 16.04 having an older libqtermwidget library.

**Comment by yan12125** [comment]
Looks like you use `pkg-config` in texstudio [1], so detecting the version should be possible via `pkg-config --atleast-version 0.9.0 qtermwidget5`. Here version 0.9.0 is the first version with `setTerminalSizeHint()` [2]

[1] https://github.com/texstudio-org/texstudio/commit/9faa44e59fa9c88ed142b22a39c3a4a5142b9077
[2] https://github.com/lxqt/qtermwidget/commit/02e1ea9702cd6c83d182a5f3e98c67dbcd6ae938

**Comment by axkibe** [comment]
Ah, yes I didn't do much with their build system, and this may be the best way out now, I guess sunderme is working on this.

Still, could you consider in future to add in qtermwidget.h a version define?
similar like https://doc.qt.io/qt-5/qtglobal.html#QT_VERSION_CHECK
only also for QTERMWIDGET_VERSION_CHECK?

**Comment by yan12125** [comment]
Hmm, seems there are issues on utilizing pkg-config on Fedora (https://github.com/texstudio-org/texstudio/issues/1008#issuecomment-605315081). It will be then reasonable to add this, but I prefer to see what happens on the Fedora package first.

**Comment by yan12125** [comment]
Okay the issue at texstudio is resolved. Feel free to leave a comment if someone finds another use case that cannot be handled by pkg-config or cmake.

**Comment by axkibe** [comment]
This depends on what kind of features you gonna change or functions to add. Many libraries have a version define, it certainly wouldn't hurt.

**Comment by yan12125** [comment]
As I have said, I'm not against adding those macros. Just that I'm not going to do that by myself in near future. If anyone is going to write a patch, the `lxqt_create_pkgconfig_file` function [1] may be a good template for how to create files automatically.

> Also the "solution" for TeXStudio was to disable the terminal widget all together, for a slightly older version, which otherwise would have worked just fine for that system, if leaving out the setTerminalSizeHint() call

I wouldn't call 0.8.0 "slightly" older. qtermwidget changed a lot in recent years and I recommend against people using such an old version.

[1] https://github.com/lxqt/lxqt-build-tools/blob/master/cmake/modules/LXQtCreatePkgConfigFile.cmake

**Comment by axkibe** [comment]
I didn't understand what solution path you had in mind, but with cmake this is a piece of cake.   #333 

(I've been using this for "about" boxes, except there I generate it as strings.)
