### ISSUE TITLE
What font does it use by default?

### ISSUE THREAD

**Issue by simonbcn** [lxqt/qtermwidget#332]
```
Operating System: Arch Linux 
KDE Plasma Version: 5.18.3
KDE Frameworks Version: 5.68.0
Qt Version: 5.14.1
qtermwidget 0.14.1-1
```

I use `konsole` with a Nerd Font to show symbols in console but programs like `Octopi` uses `qtermwidget` to execute certain commands. My terminal prompt and some output in `qtermwidget` is wrong:
![captura_20200329_114139](https://user-images.githubusercontent.com/428231/77845858-468d3c80-71b2-11ea-91b4-df89fbcff439.png)

What font does `qtermwidget` use by default? How can I change the font that `qtermwidget` uses?

**Comment by shaneramone** [comment]
I am having the same issue. I wonder if there exists a configuration file where one can change the fonts and colour schemes for qtermwidget etc.?

I also use konsole as my terminal emulator but I require qtermwidget as it is used as the integrated terminal for octopi. I would be very pleased if qtermwidget was able to use the font and colour scheme from konsole.

**Comment by yan12125** [comment]
The default font on systems other than macOS is `Monospace` [1]. In general it is a special alias, which is resolved as the default monospace font on your system. That can be changed with a qtermwidget API `setTerminalFont()` [2]. You'll need to talk to Octopi developers for adding an option for users.

> I would be very pleased if qtermwidget was able to use the font and colour scheme from konsole.

qtermwidget does not handle configurations by itself. That is done by applications use it. That will be a feature request to Octopi, too. (ref: `setColorScheme()` [3])

[1] https://github.com/lxqt/qtermwidget/blob/11c706d3ad7807d5a85ec906f75b9ad2007cd535/lib/qtermwidget.cpp#L40
[2] https://github.com/lxqt/qtermwidget/blob/11c706d3ad7807d5a85ec906f75b9ad2007cd535/lib/qtermwidget.h#L86
[3] https://github.com/lxqt/qtermwidget/blob/11c706d3ad7807d5a85ec906f75b9ad2007cd535/lib/qtermwidget.h#L112
