### ISSUE TITLE
If the PS1 path is too long, change the size of the terminal window left and right, multiple lines will appear

### ISSUE THREAD

**Issue by KingsWorldProject** [lxqt/qtermwidget#358]
[

##### Expected Behavior

Terminal Resizing，PS1 path will not change

ut000745@ut000745-PC:~/Desktop/terminate/build-deepin-terminal-unknown-Debug$ 

##### Current Behavior

cuY will increase
ut000745@ut000745-PC:~/Desktop/terminate/build-deepin-terminal-unknow

ut000745@ut000745-PC:~/Desktop/terminate/build-deepin-terminal-unknow

ut000745@ut000745-PC:~/Desktop/terminate/build-deepin-terminal-unknown

ut000745@ut000745-PC:~/Desktop/terminate/build-deepin-terminal-unknown-

ut000745@ut000745-PC:~/Desktop/terminate/build-deepin-terminal-unknown-D

ut000745@ut000745-PC:~/Desktop/terminate/build-deepin-terminal-unknown-Deb

ut000745@ut000745-PC:~/Desktop/terminate/build-deepin-terminal-unknown-Debu

ut000745@ut000745-PC:~/Desktop/terminate/build-deepin-terminal-unknown-Debug

ut000745@ut000745-PC:~/Desktop/terminate/build-deepin-terminal-unknown-Debug$

ut000745@ut000745-PC:~/Desktop/terminate/build-deepin-terminal-unknown-Debug

ut000745@ut000745-PC:~/Desktop/terminate/build-deepin-terminal-unknown-Debu

ut000745@ut000745-PC:~/Desktop/terminate/build-deepin-terminal-unknown-Deb

##### Possible Solution

When the size of the terminal window is actively changed, the new line display is reprocessed
##### Steps to Reproduce (for bugs)

1. Set up a long PS1 path
2. Change the terminal size to the left or right
3. 
4. 

##### System Information

* Distribution & Version: 
* Kernel: 
* Qt Version: 
* lxqt-build-tools Version: 
* Package version:

**Comment by yan12125** [comment]
Thanks for detailed bug report. This will no longer an issue after https://github.com/lxqt/qterminal/issues/76 is implemented, and most likely fixing this is almost as hard as implementing issue 76, so I consider this a duplicate.
