### ISSUE TITLE
Disable showResizeNotification

### ISSUE THREAD

**Issue by willbelr** [lxqt/qtermwidget#388]
##### Expected Behavior
No notification shown when the window is resized

##### Current Behavior
Notification is shown every time the terminal is resized (ie. Size: 100 x 100)

##### Possible Solution
Add a switch to skip call to showResizeNotification() function in TerminalDisplay.cpp (line 1795)

Thank you !

**Comment by yan12125** [comment]
You can use `setTerminalSizeHint(false)` ;)

**Comment by stefonarch** [comment]
1) in the GUI there is the option in v 0.16.1
2) it doesn't have effect, neither in GUI neither in file setting.
Not sure as this is on qterminal-741 branch
![schermata-10-21-36](https://user-images.githubusercontent.com/10681413/102685909-2c820700-41e4-11eb-882d-00f706f29827.png)

**Comment by willbelr** [comment]
> You can use `setTerminalSizeHint(false)` ;)

I missed that somehow, thanks.

**Comment by yan12125** [comment]
> it doesn't have effect

It might be another issue. That option has been working fine for me.

> I missed that somehow, thanks.

Glad to help :)

**Comment by stefonarch** [comment]
> It might be another issue. That option has been working fine for me.

It is - I see it works fine on my debian box but not in arch.
