### ISSUE TITLE
lxqt-build-tools version "0.8.0" required for compilation?

### ISSUE THREAD

**Issue by mcondarelli** [lxqt/qtermwidget#402]
Apparently build instructions are a bit off.
They state:

The only runtime dependency is qtbase ≥ 5.7.1. In order to build CMake ≥ 3.0.2 and lxqt-build-tools >= 0.4.0 are needed as well as Git to pull translations and optionally latest VCS checkouts.

But I get:

```
mcon@cinderella:~/projects/qtermwidget/build$ cmake ..
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:39 (find_package):
  Could not find a configuration file for package "lxqt-build-tools" that is
  compatible with requested version "0.8.0".

  The following configuration files were considered but not accepted:

    /usr/share/cmake/lxqt-build-tools/lxqt-build-tools-config.cmake, version: 0.6.0



-- Configuring incomplete, errors occurred!
See also "/home/mcon/projects/qtermwidget/build/CMakeFiles/CMakeOutput.log".
```

I am running on a fairly up-to date Linux Mint 20.1 "Ulyssa".
My distribution already has binary distribution for qtermwidget, my only interest in compiling is I need to use this from Python (either PyQt5 or Pyside) and I was not able to find relevant bindings while I understand they should be available recompiling.

Build instructions for Python would be much appreciated.
I could help in preparing a setup.py suitable for general consumption (i.e.: for PyPi)

Thanks In Advance
Mauro

**Comment by mcondarelli** [comment]
Update:
I have been able to overcome the above problem by manually lowering requirements in CMaleLists.txt, but I'm far from confident that is a good idea.

I also tried to build the PyQt5 bindings, but I got a bad error (apparently unrelated to the above):

```
mcon@cinderella:~/projects/qtermwidget/buildpy$ cmake ../pyqt/
CMake Warning (dev) in CMakeLists.txt:
  No project() command is present.  The top-level CMakeLists.txt file must
  contain a literal, direct call to the project() command.  Add a line of
  code such as

    project(ProjectName)

  near the top of the file, but after cmake_minimum_required().

  CMake is pretending there is a "project(Project)" command on the first
  line.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PythonInterp: /usr/bin/python (found version "3.8.5") 
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.8.so (found version "3.8.5") 
-- Python system site-packages directory: /usr/lib/python3/dist-packages
-- The Python files will be installed to /usr/local/lib/python3/dist-packages. Make sure to add them to the Python search path (e.g. by setting PYTHONPATH)
-- Found PythonLibrary: /usr/lib/x86_64-linux-gnu/libpython3.8.so  
-- Found SIP configuration but the sip executable could not be found.
Traceback (most recent call last):
  File "/home/mcon/projects/qtermwidget/pyqt/cmake/FindPyQt5.py", line 31, in <module>
    pyqt_sip_dir = next(
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mcon/projects/qtermwidget/pyqt/cmake/FindPyQt5.py", line 36, in <module>
    raise RuntimeError("Cannot find QtCore/QtCoremod.sip from candidates: " + repr(candidates))
RuntimeError: Cannot find QtCore/QtCoremod.sip from candidates: ['/usr/local/lib/python3.8/dist-packages/PyQt5/bindings', '/usr/share/sip/PyQt5']
-- Found PyQt5 version: 5.14.1
CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.16)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring done
-- Generating done
-- Build files have been written to: /home/mcon/projects/qtermwidget/buildpy
mcon@cinderella:~/projects/qtermwidget/buildpy$ make
Scanning dependencies of target __home_mcon_projects_qtermwidget_buildpy____pycache_____init__.cpython-38.pyc
Byte-compiling /home/mcon/projects/qtermwidget/buildpy//__init__.py to /home/mcon/projects/qtermwidget/buildpy//__pycache__/__init__.cpython-38.pyc
[  0%] Built target __home_mcon_projects_qtermwidget_buildpy____pycache_____init__.cpython-38.pyc
CMakeFiles/python_module_QTermWidget.dir/build.make:71: *** missing separator.  Stop.
make[1]: *** [CMakeFiles/Makefile2:104: CMakeFiles/python_module_QTermWidget.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
mcon@cinderella:~/projects/qtermwidget/buildpy$ 
```
Any hint welcome.
TiA!

**Comment by mcondarelli** [comment]
Update2:
I managed to have an apparently working version of QTermWidget.

I am uneasy with it thou as I had to compile with:

    CPLUS_INCLUDE_PATH='/usr/include/x86_64-linux-gnu/qt5:/usr/include/x86_64-linux-gnu/qt5/QtCore:/usr/include/x86_64-linux-gnu/qt5/QtGui:/usr/include/x86_64-linux-gnu/qt5/QtWidgets:../build:/home/mcon/projects/qtermwidget/build/lib' make

which surely does not look right.

Explicit build instructions would be most welcome.
I will not venture in building for pyside2/pyside6 without some directions.

Thanks.

**Comment by yan12125** [comment]
> lxqt-build-tools version "0.8.0" required for compilation?

> I have been able to overcome the above problem by manually lowering requirements in CMaleLists.txt, but I'm far from confident that is a good idea.

Yes, qtermwidget targets only the latest version of lxqt-build-tools. Older version may work but not recommended.

> Build instructions for Python would be much appreciated.

Currently PyQt bindings should be built together with the main library using the cmake option `QTERMWIDGET_BUILD_PYTHON_BINDING=ON`. Our CI script for Arch Linux may help https://github.com/lxqt/qtermwidget/blob/master/.ci/build.sh

> I could help in preparing a setup.py suitable for general consumption (i.e.: for PyPi)

That is much appreciated! Leave a comment at https://github.com/lxqt/qtermwidget/issues/364 is you have anything to discuss/share/etc.

> I also tried to build the PyQt5 bindings, but I got a bad error (apparently unrelated to the above):

> I am uneasy with it thou as I had to compile with:

Thanks for testing. Include paths should be correctly set with `QTERMWIDGET_BUILD_PYTHON_BINDING=ON`

> I will not venture in building for pyside2/pyside6 without some directions.

Currently only there are only PyQt bindings. PySide2 is requested (https://github.com/lxqt/qtermwidget/issues/249) while not solved.

**Comment by mcondarelli** [comment]
I am unsure if this is the right place to ask, please redirect me as needed.

I have multiple problems with QTermWidget:

- I was unable to find documentation, I resorted to using  qtermwidget/pyqt/sip/qtermwidget.sip as reference, but that's "suboptimal".
- I was unable to find a way (if it exists) to reformat wrapped lines on widget resize (something like gnome-term).
- I am getting a *very* strange behavior executing a bash script in QTermWidget subprocess:
I call the script as:
```python
            term.clear()
            term.setWorkingDirectory(cwd)
            term.connect('bash', [scriptfile])
            term.setShellProgram('bash)
            term.setArgs([scriptfile])
            term.startShellProgram()
```
Script (working fine if called directly) starts as:
```bash
#!/bin/bash -x
set -e
set -x

here=$(pwd)
echo $here
cat $here/config

if [ -z "$APP_PATH" ]
then
    if [ -f config ]
    then
        source $here/config
    fi
else
...
```
but it bombs with:
```
+ pwd
+ here=/home/mcon/vocore/__V2__/Buildroot-2
+ echo /home/mcon/vocore/__V2__/Buildroot-2
/home/mcon/vocore/__V2__/Buildroot-2
+ cat /home/mcon/vocore/__V2__/Buildroot-2/config
APP_PATH=/home/mcon/vocore/Applicazione
+ [ -z  ]
+ [ -f config ]
+ source /home/mcon/vocore/__V2__/Buildroot-2/config
/home/mcon/vocore/__V2__/Buildroot-2/08-Build_update2v2: 16: source: not found
```
Is there any way this could be linked to QTermWidget? 

TiA!
