### ISSUE TITLE
Proposal: Replace the forked PTY code with upstream KDE/kpty

### ISSUE THREAD

**Issue by librehat** [lxqt/qtermwidget#428]
##### Expected Behavior
This project was forked from the old Konsole code. These days, KDE Frameworks have been modularised and [kpty](https://github.com/KDE/kpty) is a maintained project with minimal dependencies (ECM and Qt) that could replace the old forked PTY code in this project.

##### Current Behavior
Old forked PTY/KPTY

##### Possible Solution
Replace the part of the current implementation with the upstream KDE/kpty library

##### Steps to Reproduce (for bugs)
N/A

##### Context
A possible solution to the lacking of `Konsolewidget` while lightening up the maintenance of this project

##### System Information
N/A

I'm willing to send in a PR but want to first see how everyone feels about this proposal

**Comment by yan12125** [comment]
Thanks for bringing this up. Moving to KPty has been discussed some time ago in https://github.com/lxqt/qterminal/issues/320, and there is a WIP branch in https://github.com/lxqt/qtermwidget/tree/kpty. However, there are different opinions in the aforementioned issue.

Closing as a duplicate.
