### ISSUE TITLE
Missing cursor implementation code causes display corruption in pacman updates for arch linux

### ISSUE THREAD

**Issue by mcloaked** [lxqt/qtermwidget#429]
For arch linux, pacman was recently updated to version 6.0.0-2 which now allows multiple parallel downloads of package update files.

pacman used to work fine in any terminal application that I used - in particular both in konsole, and also qterminal running in plasma desktop. After the update to pacman 6.0.0-2 when running a pacman -Syu update in a konsole window works as before, but in qterminal the download progress bar now doubles up each download line and looks rather untidy and messy. The updates work fine, and it is just the presentation of the download progress that seems to be corrupted in qterminal. 

This appears to be due to lines 669 and 670  in https://github.com/lxqt/qtermwidget/blob/master/lib/Vt102Emulation.cpp which has:

case TY_CSI_PN('E'      ) : /* Not implemented: cursor next p lines */         break; //VT100
case TY_CSI_PN('F'      ) : /* Not implemented: cursor preceding p lines */    break; //VT100

This needs to be implemented instead of being 'Not implemented'  in order for pacman to work correctly when executed in qterminal.

##### Expected Behavior

pacman -Syu when executed in qterminal should display correctly when running multiple parallel downloads.

##### Current Behavior

The lines for multiple parallel download of package update files displays as broken into more than one line for each package being downloaded.

##### Possible Solution

This appears to be due to lines 669 and 670  in https://github.com/lxqt/qtermwidget/blob/master/lib/Vt102Emulation.cpp which has:

case TY_CSI_PN('E'      ) : /* Not implemented: cursor next p lines */         break; //VT100
case TY_CSI_PN('F'      ) : /* Not implemented: cursor preceding p lines */    break; //VT100

This needs to be implemented instead of being 'Not implemented'  in order for pacman to work correctly when executed in qterminal.

##### Steps to Reproduce (for bugs)

Open qterminal in arch linux and execute pacman -Syu to update a system with more then one package when using pacman version 6.0.0-2 or later.

1. 
2. 
3. 
4. 

##### Context

I am simply updating my arch linux system and the package manager should display correctly (which works fine in konsole but not in qterminal).

##### System Information

Arch linux - with versions of qterminal and pacman:

qterminal 0.17.0-1
pacman 6.0.0-2

* Distribution & Version: Arch linux current and up to date on all packages
* Kernel: 5.12.8-1
* Qt Version: qt5-base 5.15.2+kde+r196-1
* lxqt-build-tools Version: 
* Package version: qterminal 0.17.0-1

**Comment by stefonarch** [comment]
Confirming, I first thought it was an video issue.

**Comment by alerque** [comment]
Per [this comment](https://bbs.archlinux.org/viewtopic.php?pid=1975828#p1975828) `konsole` implements this already, so the handling just needs porting over.

Note that the title and multiple references in the body are kind of misleading: **this is not a Pacman or Arch Linux specific issue**, it is just lacking a standard escape sequence feature that is also used by other non Pacman non-Arch Linux projects. The users above just don't happen to use any of them.

**Comment by mcloaked** [comment]
Perhaps, since qterminal already uses the konsole source code, as you say, it is presumably the case that if qterminal is updated to use current konsole source code this issue would be resolved. It is just that the recent update to pacman in arch linux has exposed the cursor escape limitations in qterminal  because the specific escapes it needs for multiline cursor movements had not been implemented when qterminal was initially written. Most common commands don't require those escapes - but it would be good for qterminal to be brought up to current spec so that it will function correctly with those commands that need the cursor escapes to work with multiline output.

**Comment by mcloaked** [comment]
I note that nobody has been assigned to this issue - once a developer is assigned perhaps it would be quite a simply update to get it working and fix the bug which has presumably always been present but until a command that needs the escapes was used the bug did not reveal itself.

**Comment by mcloaked** [comment]
Since I wasn't sure if this should be reported for qterminal itself I have put an issue in to https://github.com/lxqt/qterminal/issues/836

**Comment by yan12125** [comment]
Created a pull request for backporting the Konsole commit. It works fine with Pacman. More testing is welcome!

**Comment by stefonarch** [comment]
Looks working fine:
![schermata-20-58-20](https://user-images.githubusercontent.com/10681413/121786581-f6d14000-cbc0-11eb-96a2-bd13851ee7fb.png)

**Comment by yan12125** [comment]
Thanks for testing! I merged it without further reviewing as it is a small backport from Konsole.

**Comment by mcloaked** [comment]
Arch linux now has the new version with the backport as version 0.17.0-2

The escapes now work perfectly and resolve this bug.
