### ISSUE TITLE
App crashes when qtermwidget is used with "setHistorySize(0)"

### ISSUE THREAD

**Issue by ChrisOboe** [lxqt/qtermwidget#456]
##### Expected Behavior
My app doesn't crash when using a qtermwidget where setHistorySize(0) was called. 

##### Current Behavior
It crashes when using a qtermwidget where setHistorySize(0) was called. 

##### Possible Solution
Checking input arguments of setHistorySize to prevent doing anything when called with 0 as argument. Or alternatively figuring out what exactly leads to the crash and fix this. 

##### Steps to Reproduce (for bugs)
use a qtermwidget somewhere
call setHistorySize(0)
execute some commands (e.g. clear).  

##### Context
I'm trying to write a terminal emulator based on qtermwidget.    --->

##### System Information
* Distribution & Version: NixOS Unstable
* Kernel: 5.15.4
* Qt Version: 5.15.3
* lxqt-build-tools Version: i don't know
* Package version: 1.0.0

**Comment by luis-pereira** [comment]
@ChrisOboe Confirmed. A fix on the way.

**Comment by luis-pereira** [comment]
@ChrisOboe Fix available at https://github.com/lxqt/qtermwidget/pull/457. Can you test it ?

**Comment by luis-pereira** [comment]
@tsujan Can you take a quick look ?

**Comment by tsujan** [comment]
@luis-pereira 
The strange thing was that I didn't receive any email notification from this repository until you called me! Activated the "watch" state; don't know how it was changed to "unwatched".

Will review the code soon.
