### ISSUE TITLE
Add support for terminal navigation with arrow keys

### ISSUE THREAD

**Issue by francescmm** [lxqt/qtermwidget#475]
##### Expected Behavior

I'd like to navigate through the terminal with the arrows of my cursor in the same way that terminals usually do:
- Up: previous entry in the history of the terminal
- Down: next entry in the history of the terminal
- Left: move the cursor to the left
- Right: move the cursor to the right

##### Current Behavior

Arrow keys are not parsed either in TerminalDisplay widget or Screen object.

##### Possible Solution

From what I've tried so far, it seems that the best solution is to capture the events generated by pressing/releasing these keys in the TerminalDisplay class. The _keyPressEvent_ method is already overwritten but doesn't parse these keys, it would be needed to add them. In addition, it might be necessary to overwrite _keyReleaseEvent_ to know when the user has released the key. It should be possible to hold a key to move the cursor in the desired direction by more than one position at a time.

##### Steps to Reproduce (for bugs)

N/A

##### Context

Trying to reproduce the behavior of a Terminal as close as possible.

**Comment by tsujan** [comment]
All of them work in QTerminal.

**Comment by francescmm** [comment]
I just tested and there has been some kind of regression related with QTermWidget. With the latest master, they don't work at all (at least for myself). With the version 0.14.1 of both QTerminal and QTermWidget, they do.

**Comment by francescmm** [comment]
Update: it seems that the regression is in the QTerminal (I might open a but there).

However I was wondering if this is something you might want to port to QTermWidget. If not, feel free to close :)

**Comment by tsujan** [comment]
There's no regression here. I have the latest git qterminal and qtermwidget.

**Comment by francescmm** [comment]
:thinking: With the latest do you mean "master" or the latest release?

**Comment by tsujan** [comment]
All LXQt devs should have the latest git (= latest master).

**Comment by francescmm** [comment]
Then I must be doing something wrong, since I was testing with master as you say.

I'll check during the week, thanks!

**Comment by tsujan** [comment]
Make sure both `qtermwidget` and `qterminal` are up-to-date (= latest master) and compiled in that order.

**Comment by yan12125** [comment]
Could you check if the kb-layouts folder is installed to `$PREFIX/share/qtermwidget5`? Files in that folder, particularly default.keytab, handles translation from key codes to escape sequences. Details can be checked in https://github.com/lxqt/qtermwidget/blob/d682d30716d4e39373eb13c7f33c5027e697ba14/lib/tools.cpp#L14

Maybe qtermwidget should support loading data files from the source tree as well.

**Comment by francescmm** [comment]
Hi @yan12125 @tsujan I've cloned again the code and did a fresh compilation and I'm not getting the issues right now. I probably messed something with the different compilations and branches.

As @tsujan says, that's implemented in QTerminal. However, I wish we could have that as part of QTermWidget along with colors, and so. It seems something rather "base" to have. And QTerminal could be all the widgets on top of the QTermWidget. At least that's what I thought it was.

**Comment by yan12125** [comment]
You seem to misunderstand tsujan :) Arrow keys are handled in qtermwidget (by `*.keytab` and relevant codes). You can build qtermwidget with `-D BUILD_EXAMPLE=ON` and use arrow keys with `./example`.

**Comment by francescmm** [comment]
Oh! Then I totally misunderstood him! I'll check that this afternoon! Thanks!

**Comment by francescmm** [comment]
@yan12125 @tsujan OMG: It worked! :D
