### ISSUE TITLE
Clicking backspace delets words instead of a letter in zsh

### ISSUE THREAD

**Issue by rahmanshaber** [lxqt/qtermwidget#483]
When i click backspace in qterminal/coreterminal it removes the whole word, I tried with bash and it doesn't happen there. But i tried zsh in gnome terminal and only delete 1 letter/alphabet with one press in the backspace key.

##### Expected Behavior

It should only delete 1 letter/alphabet with one press in the backspace key.

##### Steps to Reproduce (for bugs)

1. type " This is not a test"
2. press backspace key once
3. it deletes the  whole "test" word
4. now the whole text is "This is not a " instead "This is not a tes"

##### System Information

* Distribution & Version: manajaro
* Kernel: 
* Qt Version: 5.15.5
* lxqt-build-tools Version: 
* Package version: 1.1.0.1

**Comment by stefonarch** [comment]
I'm  not used to zsh but every time I use a manjaro live edition in Vbox I get disturbed by exactly this behaviour.
So I assume that there are zsh keybindings to fix and it has nothing to do with qterminal, see https://unix.stackexchange.com/questions/604348/backspace-deletes-a-whole-word-zsh

Look for `bindkey '^H' backward-kill-word` in your `~/.zsh`

**Comment by rahmanshaber** [comment]
>Look for bindkey '^H' backward-kill-word in your ~/.zsh

this file doesn't exist 

![image](https://user-images.githubusercontent.com/30831735/177049109-a19a488d-9fca-4d85-9ba4-eacf5a5bb5a3.png)

**Comment by stefonarch** [comment]
That means you're probably using the default file in /usr/share/zsh/manjaro-zsh-configm cppy it to `~/.zshrc` and edit it to your needs.

**Comment by rahmanshaber** [comment]
it's set ctrl+backspace but i am not pressing any combination

![image](https://user-images.githubusercontent.com/30831735/177050666-46a9fe3d-7579-4ade-9b4c-da79a8ed984e.png)
