### ISSUE TITLE
The scrollbar elevator cart isn’t visible (even when hovering the elevator shaft)

### ISSUE THREAD

**Issue by da2x** [lxqt/qtermwidget#486]
##### The problem
I’m struggling to locate the scrollbar elevator cart and to use it as a positional indicator. It’s especially difficult when I don’t know approximately where in the shaft its located.

##### Current Behavior
The scrollbar elevator only becomes visible when it’s hovered.

##### Possible Solution

If auto-hiding scrollbars are enabled (or low contrast), then the elevator should be light up when hovering the scrollbar shaft to help locate it.

Alternatively: The scrollbar elevator should remain visible at all time. It’s always visible in Konsole; where it’s a light gray (it’s invisible in QTerminal) and turns blue when hovered (same as QTerminal).

![Screenshot 1 (invisible scrollbar elevator)](https://user-images.githubusercontent.com/1102886/187856529-06f4598f-516e-4531-b139-4f265d9b8d98.png)
![Screenshot 2 (visible/hovered scrollbar elevator)](https://user-images.githubusercontent.com/1102886/187856545-09b0f0bb-2285-43df-bbd5-12c2191e93f8.png)

![Screenshot 3 (Konsole, for reference)](https://user-images.githubusercontent.com/1102886/187858087-da720d6a-8e16-4eda-9625-cc13e02f9bef.png)

AFAIK, I’m using the default Plasma theme without any stylistic customization (except increasing the size of the mouse cursor).

##### System Information
* Distribution & Version: Fedora 36
* Kernel: 5.19.4-200.fc36.x86_64
* Qt Version: 5.15.5
* lxqt-build-tools Version: N/A
* Package version: 1.0.0

**Comment by tsujan** [comment]
This isn't related to QTerminal but to KDE's Breeze style and KDE's color schemes.

**Comment by da2x** [comment]
Any tips on how to fix it?

**Comment by tsujan** [comment]
You could change QTerminal → Preferences → Color scheme to a light(er) one if you don't want to change Breeze or its color scheme in KDE System Settings.

You can also change QTerminal → Preferences → Widget style to Fusion or another style, but that will make QTerminal look different from other apps if you work under KDE.

**Comment by da2x** [comment]
All the dark color schemes with the same names have a visible elevator car in Konsole, though. The same themes (at least thet have the same names) get a dark and nearly invisible elevator car in QTerminal. The light color schemes behave the same in both apps.

I looked through the colorscheme files but didn’t see anything obvious named “scrollbars”. Is the scrollbar color automatically chosen from the background color? or is it set by one of the generic sounding properties? or by something internal in the toolkit?
