### ISSUE TITLE
ImportError: libqtermwidget5.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by MrAntonS** [lxqt/qtermwidget#497]
After compiling python package and installing it using pip install, when i try to import the widget to python, it returns this error, and i'm not sure how to fix this. I'm using last version of Arch linux if this of any use.

**Comment by yan12125** [comment]
Did you install the qtermwidget package? It provides `/usr/lib/libqtermwidget5.so.1`.

By the way, you can also use the Python library provided in the qtermwidget pacakge.

**Comment by yan12125** [comment]
> I did build it, mostly following the shell script for python build.

Do you mean `.ci/build.sh`? The current script is missing installation steps. I added some fixes here: https://github.com/lxqt/qtermwidget/blob/expand-ci-script/.ci/build.sh

> Am i supposed to run anything else like makepkg?

makepkg is not necessary, but makes things easier.

**Comment by MrAntonS** [comment]
Thank you, I will test it as soon as possible, currently, after I installed qterm after aur and they compiled wheel and installed it with pip install it worked, but I will check if this will also do the job, thank you

**Comment by yan12125** [comment]
I assume issues are resolved. Feel free to leave comments if not.
