### ISSUE TITLE
Builtin close() method does not destroy QTermWidget gracefully

### ISSUE THREAD

**Issue by willbelr** [lxqt/qtermwidget#535]
When `close()` method is called on QTermWidget, it appears to close, yet the widget is not deleted properly.

##### Expected Behavior
`close()` method should close and delete the widget gracefully, so that memory is freed and garbage collected in Python.

##### Current Behavior
Despite that the `close()` method makes the widget disappear, it is not destroyed until the parent object is deleted. At this moment, an error message is thrown: `virtual KPtyProcess::~KPtyProcess() the terminal process is still running, trying to stop it by SIGHUP`

##### Steps to Reproduce
In the example below, QTermWidget is added to a QMainWindow. When `close` is called on QTermWidget, it disappear as expected, without error. However, as either `deleteLater` is called on the terminal (_trigger 1_), or `close` is called on the container widget (_trigger 2_), this error is shown;

`virtual KPtyProcess::~KPtyProcess() the terminal process is still running, trying to stop it by SIGHUP`

```
#!/usr/bin/env python3
import sys
from PyQt5 import QtWidgets, QtCore
from QTermWidget import QTermWidget


class Container(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        self.term = Terminal()
        self.setCentralWidget(self.term)
        self.show()
        QtCore.QTimer.singleShot(5000, self.close)  # Trigger 2


class Terminal(QTermWidget):
    def __init__(self):
        super().__init__(1)
        QtCore.QTimer.singleShot(1000, self.close)  # No error
        QtCore.QTimer.singleShot(2000, self.deleteLater)  # Trigger 1


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    container = Container()
    app.exec()
```

##### System Information
* Distribution & Version: Arch Linux
* Kernel: Linux 6.6.10-arch1-1 x86_64 GNU/Linux
* Qt Version: 5.15.12-1
* Python Version: 3.11.6-1
* lxqt-build-tools Version: 0.13.0-1
* Package version: 1.4.0-1

**Comment by tsujan** [comment]
Fixed in https://github.com/lxqt/qtermwidget/commit/0ff7b19bea4767cbbad2cae1558330e2927e7473
