### ISSUE TITLE
PyQT5 bindings fail with error  - qtermwidget.sip:14:10: fatal error: qtermwidget.h: No such file or directory

### ISSUE THREAD

**Issue by nado218** [lxqt/qtermwidget#557]
Hi,
I'm new to pyQT and I'm trying to build python bindings for QtermWidget.
I could compile and install qtermwidget library but when i try to create a python wheel using sip-wheel --verbose, i get the below error.
What I'm I missing here. 
My Qtermwidget is installed in installed to the default - /usr/local/

Below is the log.

cd QTermWidget/ && ( test -e Makefile || /usr/lib/qt5/bin/qmake -o Makefile /tmp/tmp0cyt8_wt/QTermWidget/QTermWidget.pro ) && make -f Makefile
make[1]: Entering directory '/tmp/tmp0cyt8_wt/QTermWidget'
g++ -c -pipe -O2 -fno-exceptions -Wall -Wextra -D_REENTRANT -fPIC -DPy_LIMITED_API=0x03080000 -DSIP_PROTECTED_IS_PUBLIC -Dprotected=public -DQT_NO_EXCEPTIONS -DQT_NO_DEBUG -DQT_PLUGIN -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -I. -I.. -I/usr/include/python3.10 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o sipQTermWidgetcmodule.o sipQTermWidgetcmodule.cpp
/home/ndokuri/Qualcomm/QT5/qtermwidget/pyqt/sip/qtermwidget.sip:14:10: fatal error: qtermwidget.h: No such file or directory
14 | #include <qtermwidget.h>
| ^~~~~~~~~~~~~~~
compilation terminated.

##### System Information

* Distribution & Version:  Ubuntu 22.04
* Kernel:   6.5.0-44-generic
* Qt Version: PyQt5
* lxqt-build-tools Version: 0.13.0
* Package version: 1.4.0

can qtermwidget be used with python on Ubuntu Linux. If yes, can you please suggest how to overcome this error during sip-wheel

**Comment by tsujan** [comment]
Please close this and use [Discussions](https://github.com/lxqt/lxqt/discussions) for questions.

Old versions aren't supported by LXQt.

**Comment by nado218** [comment]
Thank you. Will check with the latest version as well.
