### ISSUE TITLE
virtual KPtyProcess::~KPtyProcess() the terminal process is still running, trying to stop it by SIGHUP

### ISSUE THREAD

**Issue by tsujan** [lxqt/qtermwidget#566]
The message of the title might happen repeatedly in the log (actually, each time a terminal window is closed) if I don't disable Qt warnings inside `~/.config/QtProject/qtlogging.ini`. It's caused by these lines in the d-tor of `KPtyProcess`:

https://github.com/lxqt/qtermwidget/blob/df7297b3e372934cfa787cc3f92db9d18ec0e00b/lib/kptyprocess.cpp#L96-L104

Qt doc [says](https://doc.qt.io/qt-6/qprocess.html#dtor.QProcess) that `QProcess::~QProcess()` will not return until the process is terminated.

IMO, waiting for the `finished()` signal inside the d-tor of a `QProcess` isn't OK. I checked KDE's `kpty` → `kptyprocess.cpp`. They either never used `waitForFinished()` there or removed it a long time ago. ~Will use QTerminal without it for a while to test…~

**Comment by tsujan** [comment]
@palinek 
This is a general question about `QProcess`. Any thought on it?

**Comment by tsujan** [comment]
Oh, it was added here 4 years ago, by @palinek: https://github.com/lxqt/qtermwidget/pull/171. Without it, this message is shown instead: `QProcess: Destroyed while process ("/bin/bash") is still running.`

Maybe another method needs to be found, because Konsole doesn't have this problem.

**Comment by marcusbritanicus** [comment]
This is a nice fix. I was about to tell something similar, but much simpler. I would have just called `_shellProcess->kill()` inside `Session::close()` and then emitted `finished()`

**Comment by tsujan** [comment]
Made it as similar to Konsole as possible because I was sure about Konsole.

The next step, after the PR is merged, is to adapt konsole's code for showing a prompt when closing the terminal with a running process in it. It shouldn't be so hard now.

**Comment by marcusbritanicus** [comment]
Yes, this is quite trivial. 

I had added a function to `QTermWidget` class, sometime [last year](https://github.com/lxqt/qtermwidget/commit/ccb3b2132d3c7d4b19b9a3221f9c4dcf13eee9dc) for this precise purpose. It's called `getForegroundProcessID()`. `QTermWidget` already has a function to get the PID of the running shell `getShellPID()`. If `getShellPID() != getForegroundProcessID()`, then warn the user.

**Comment by tsujan** [comment]
Good to know that; thanks!

If I correctly remember, Konsole also subclasses `Session`, but we may not need that, because our GUI code (in qterminal) is very different.
