### ISSUE TITLE
(Request) - Add Kali-Dark theme from  previous qtermiwidget5 to qtermwidget6

### ISSUE THREAD

**Issue by sagisar1** [lxqt/qtermwidget#577]
Hello, I have upgraded my qterminal app in kali linux from version 1.4.1 if i am not wrong, to 2.1.0 lately. When I opened the terminal, I saw that background has a white color. I searched for the favorite Kali-Dark theme in the preferences but couldn't find it. After almost two hours of troubleshooting, I understood that it was removed in qtermwidget version 6, which qterminal version 2.1.0 works with, and that's why it's not there. I managed to fix it just by copying the theme from the qtermwidget5 directory to the qtermwidget6 direcotory, and then the theme was available in the preferences of the terminal.

##### Expected Behavior
Kali-Dark theme for qterminal should be available in the appearence section of  the qterminal preferences

##### Current Behavior
Kali-Dark theme for qterminal is not available in the appearence section of the qterminal preferences

##### Possible Solution (very eeasy to implement)
Just add the Kali-Dark theme file, which is **Kali-Dark.colorscheme** from qtermwidget5, to this repository, to the /lib/color-schemes directory (in my system, the theme file is located in **/usr/share/qtermwidget5/color-schemes/**) , to allow users to use this theme without the need to copy the file from the **qtermwidget5** directory to the **qtermwidget6** direcotory in the system.

##### Steps to Reproduce:
1. If you have qterminal version 2.1.0 (latest version), open a terminal
2. In the upper bar of the terminal, click on  **File->Preferences..**
3. Under Appearences section, you will see the "Color scheme" option
4. Kali-Dark theme is not avaiable like in the previous versions of qterminal in kali linux

##### System Information

* Distribution & Version: kali linux - version 2024.4
* Kernel:  Linux kali 6.11.2-amd64
* Qt Version:  verison 6 (used by qterminal)
* lxqt-build-tools Version:  not installed
* Package version: libqtermwidget6-2:amd64  2.1.0-1

**Comment by tsujan** [comment]
QTerminal never had a Kali-Dark theme. Most probably, your distro had added it. You might want to report this to kali linux.
