### ISSUE TITLE
Set terminal environment does not appear to be working.

### ISSUE THREAD

**Issue by Levi-Armstrong** [lxqt/qtermwidget#64]
I have created a QTermWidget and I set the working directory and environment prior to starting the shell program but when I print the environment variable from within the terminal using env they are not the same as what I set. Is this the correct way to set the terminal environment?

```
  QTermWidget &terminal = ROSManager::instance()->startTerminal(0, QString::fromLatin1("%1 %2 %3").arg(m_command, m_package, m_target));

  terminal.setWorkingDirectory(rp->projectDirectory().toString());
  terminal.setEnvironment(bc->environment().toStringList());

  //start bash now that everything is setup
  terminal.startShellProgram();

  //send roslaunch command
  terminal.sendText(command);
```

**Comment by Levi-Armstrong** [comment]
I have been able to track down that the underlying QProcess(Class KProcesss) has the environment that I passed but I am not familiar enough with the code to know where else to look. Where else should I be looking?

**Comment by f2404** [comment]
My terminal gets the environment variable if I set it just before calling `startShellProgram()` at https://github.com/lxde/qterminal/blob/master/src/termwidget.cpp#L71
Hope this helps.

**Comment by Levi-Armstrong** [comment]
I have found that I can set some environment variables but when I try to set a few of them it just defaults back to the system environment variables. It looks like you are doing your own parsing of the list but I have not had a chance to look into the code. I appears that maybe an error is occurring with the QTermWidget::setEnvironment which then it defaults back to the system environment variables.

**Comment by Levi-Armstrong** [comment]
@f2404 I have been trying to track down what the issue is but I can't seem to find anything useful. I did a test case to see if maybe it was with QProcess but the example below worked. Is there another place that the environment variable are being checked to see if they are valid? I have found on some environment variables I can set it to anything but what I want to set it to. It seems that there may be another check somewhere that I cannot find in the code. Any ideas? 

```
  QProcess test;
  test.setWorkingDirectory(rp->projectDirectory().toString());
  test.setEnvironment(bc->environment().toStringList());
  test.start(QLatin1String("bash"));
  test.waitForStarted();
  QString cmd = QLatin1String("env > /tmp/rosqtenv2.txt");
  test.write(cmd.toLatin1());
  test.closeWriteChannel();
  test.waitForFinished();
```

**Comment by Levi-Armstrong** [comment]
@f2404 Since this using some of the Konsole code, is it kept up to date with bug fixes or has deviated from Konsole to where the bug fixes are not valid?

**Comment by f2404** [comment]
@Levi-Armstrong As far as I can tell, it has deviated a lot, and I'm not seeing anyone backporting code from Konsole on a regular basis.

**Comment by Levi-Armstrong** [comment]
@f2404 Thank you, I am still trying to track down my issues. Should copy and past be working within the terminal?
CTRL+SHIFT+C and CTRL+SHIFT+V

**Comment by f2404** [comment]
@Levi-Armstrong Both copy and paste are working for me.

**Comment by Levi-Armstrong** [comment]
@f2404; did you test the copy/paste just using this package(QTermWidget) or was it done using the QTerminal? From what I can tell the copy/paste is implemented in the QTerminal not the QTermWidget; is this correct?

**Comment by agaida** [comment]
@Levi-Armstrong - btw. i see your debian branch - if interested you could try the lxqt-snapshot/latest packaging from debian https://anonscm.debian.org/cgit/pkg-lxqt/qtermwidget.git/?h=lxqt-snapshots/latest

**Comment by Levi-Armstrong** [comment]
@agaida, Thank you so much this helps a lot. Is there a ppa associated to these Debian's?

**Comment by agaida** [comment]
no, not really - but if you like to keep track with the latest development on debian systems in the widest sense this would be the way to go - have a look at debian/get-snapshot.

On ubuntu and derivatives you just have to comile, it should just work™. The dependencies should work. Hmm - ok, maybe we should talk about the sorting of the builds - bwt, i implemented this for all lxqt packages

**Comment by Levi-Armstrong** [comment]
@agaida I am new to creating Debian's, do you mind explaining what these files do in your debian folder? When I include them in my build I receive an error also listed below. I am going through this process as a learning experience.

libqtermwidget5-0-dev.install
libqtermwidget5-0.install
qtermwidget5-data.install

Error: 
dh_install: usr/share/qtermwidget5/kb-layouts/linux.keytab exists in debian/tmp but is not installed to anywhere

**Comment by agaida** [comment]
@Levi-Armstrong you should really join OFTC #debian-lxqt - and regarding your question. We believe that all files that are created in a build should be handled in some way - so we added the --fail-missing in the rules. That means: the build fails, when one or more files are not in the install of a package (simplified).

**Comment by Levi-Armstrong** [comment]
It does not look I am able to join from work. Do you have any ideas on how I may resolve the error? I see that the files are installed in the CMakeList.txt.

**Comment by Levi-Armstrong** [comment]
>@Levi-Armstrong - btw. i see your debian branch - if interested you could try the lxqt-snapshot/latest packaging from debian ��lxqt-snapshots/latest

@agaida am I able to download a Debian from the link you provided?

**Comment by agaida** [comment]
https://anonscm.debian.org/git/pkg-lxqt/qtermwidget.git
git://anonscm.debian.org/pkg-lxqt/qtermwidget.git

you will be able to clone, fetch and pull, not to push (btw. https://anonscm.debian.org/git/pkg-lxqt/ )
