### ISSUE TITLE
Should Ctrl+Shift+C be sending a sigterm signal?

### ISSUE THREAD

**Issue by Levi-Armstrong** [lxqt/qtermwidget#82]

**Comment by yan12125** [comment]
I don't think it's possible for qtermwidget/qterminal. SIGINT is sent by the kernel, where the key to use can be configured by `stty`, and there's no option for SIGTERM. If you know a terminal can do this, please tell me.

**Comment by DonnieWest** [comment]
@yan12125 I think the original request was talking about how Ctrl+C and Ctrl+Shift+C all send the same signal to the terminal. It's the same with Ctrl+V and Ctrl+Shift+V, which means I can't directly configure those to do anything differently.

In Xterm I have it set up so that Ctrl+Shift+C copies and Ctrl+Shift+V pastes so I don't accidentally close the application I'm copying from and ideally in qtermwidget I would get the same

**Comment by yan12125** [comment]
By defaut Ctrl+Shift+C triggers copying in qtermwidget. That can be configured in preferences.

**Comment by DonnieWest** [comment]
@yan12125 maybe I'm missing something? Here's a minimal example:

```
#include <QApplication>
#include <QDesktopServices>
#include <QKeySequence>
#include <QMainWindow>
#include <QtDebug>

#include "qtermwidget.h"

int main(int argc, char *argv[]) {
  QApplication app(argc, argv);
  QMainWindow *mainWindow = new QMainWindow();
  setenv("TERM", "xterm-256color", 1);

  QTermWidget *console = new QTermWidget();

  QFont font = QApplication::font();
  font.setFamily("monospace");
  font.setPixelSize(22);
  font.setWeight(QFont::Normal);

  console->setTerminalFont(font);
  console->setAutoClose(true);

  QObject::connect(console, &QTermWidget::termKeyPressed, mainWindow,
                  [=](const QKeyEvent *key) -> void {
                    qDebug() << key->text();
                    if (key->text() == "\u0003") {
                      console->copyClipboard();
                    } else if (key->text() == "\u0016") {
                      console->pasteClipboard();
                    }
                  });

  mainWindow->resize(1800, 3200);
  mainWindow->setCentralWidget(console);

  QObject::connect(console, SIGNAL(finished()), mainWindow, SLOT(close()));

  mainWindow->show();

  return app.exec();
}
```

If you look at the output of `qDebug` you'll see that Ctrl+Shift+C emits the same thing as Ctrl+C. It's possible I'm missing something though?

**Comment by yan12125** [comment]
Sorry I was wrong. Ctrl+Shift+C is handled by qterminal, not qtermwiget.

**Comment by rafaelsilverioit** [comment]
Can you provide an example of that @yan12125 using qterminal, please?
